# Generated by Django 4.2 on 2025-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='followed_farmers',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='verification/'),
        ),
    ]
