# Generated by Django 4.2 on 2025-09-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_conflicting_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='proof_of_farming',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_location',
            field=models.CharField(max_length=200),
        ),
    ]
